### ISSUE TITLE
Missing field `args.dockerfile` in container action

### ISSUE THREAD

**Issue by nikola-jokic** [fhammerl/runner-hooks#89]
**Describe the bug**
I have been using this workflow:
```
name: TEST

on:
  workflow_dispatch:

jobs:
  prepare-job:
    runs-on: self-hosted
    steps:
    - name: Setup cluster
      run: echo 'workflow'
      shell: bash
    - name: test
      uses: nikola-jokic/composite/cont@main
    - name: finish
      run: echo 'test'
```
It refers to my public repo for composite action, and the directory cont containing docker action. The `action.yaml` content:
```
name: 'Hello world'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
```
This will trigger the request to the hook, logged as:
```
{
  image: 'Dockerfile',
  entryPointArgs: [ '', '"World"' ],
  entryPoint: null,
  workingDirectory: '/github/workspace',
  createOptions: null,
  registry: { username: null, password: null, serverUrl: null },
  environmentVariables: {
    'INPUT_WHO-TO-GREET': 'World',
    HOME: '/github/home',
    GITHUB_JOB: 'prepare-job',
    GITHUB_REF: 'refs/heads/main',
    GITHUB_SHA: '40801bca4143d033009f227ac69eaa58bf056292',
    GITHUB_REPOSITORY: 'nikola-jokic/my-hook-test',
    GITHUB_REPOSITORY_OWNER: 'nikola-jokic',
    GITHUB_RUN_ID: '2429996676',
    GITHUB_RUN_NUMBER: '21',
    GITHUB_RETENTION_DAYS: '90',
    GITHUB_RUN_ATTEMPT: '1',
    GITHUB_ACTOR: 'nikola-jokic',
    GITHUB_WORKFLOW: 'TEST',
    GITHUB_HEAD_REF: '',
    GITHUB_BASE_REF: '',
    GITHUB_EVENT_NAME: 'workflow_dispatch',
    GITHUB_SERVER_URL: 'https://github.com/',
    GITHUB_API_URL: 'https://api.github.com/',
    GITHUB_GRAPHQL_URL: 'https://api.github.com/graphql',
    GITHUB_REF_NAME: 'main',
    GITHUB_REF_PROTECTED: 'false',
    GITHUB_REF_TYPE: 'branch',
    GITHUB_WORKSPACE: '/github/workspace',
    GITHUB_ACTION: '__nikola-jokic_composite',
    GITHUB_EVENT_PATH: '/github/workflow/event.json',
    GITHUB_ACTION_REPOSITORY: 'nikola-jokic/composite',
    GITHUB_ACTION_REF: 'main',
    GITHUB_PATH: '/github/file_commands/add_path_6d6a6372-3885-4e02-93b6-662babffa836',
    GITHUB_ENV: '/github/file_commands/set_env_6d6a6372-3885-4e02-93b6-662babffa836',
    GITHUB_STEP_SUMMARY: '/github/file_commands/step_summary_6d6a6372-3885-4e02-93b6-662babffa836',
    RUNNER_OS: 'Linux',
    RUNNER_ARCH: 'X64',
    RUNNER_NAME: 'hooks',
    RUNNER_TOOL_CACHE: '/home/nikola/Projects/runner-hooks/_layout/_work/_tool',
    RUNNER_TEMP: '/home/nikola/Projects/runner-hooks/_layout/_work/_temp',
    RUNNER_WORKSPACE: '/home/nikola/Projects/runner-hooks/_layout/_work/my-hook-test',
    ACTIONS_RUNTIME_URL: 'https://pipelines.actions.githubusercontent.com/1Y92N8o45480EIlygr1QaW3W2MwOA7mxmz6uVB024zxQsuulhu/',
    ACTIONS_RUNTIME_TOKEN: '***',
    ACTIONS_CACHE_URL: 'https://artifactcache.actions.githubusercontent.com/1Y92N8o45480EIlygr1QaW3W2MwOA7mxmz6uVB024zxQsuulhu/'
  },
  portMappings: [],
  systemMountVolumes: [
    {
      userProvidedValue: null,
      sourceVolumePath: '/var/run/docker.sock',
      targetVolumePath: '/var/run/docker.sock',
      readOnly: false
    },
    {
      userProvidedValue: null,
      sourceVolumePath: '/home/nikola/Projects/runner-hooks/_layout/_work/_temp/_github_home',
      targetVolumePath: '/github/home',
      readOnly: false
    },
    {
      userProvidedValue: null,
      sourceVolumePath: '/home/nikola/Projects/runner-hooks/_layout/_work/_temp/_github_workflow',
      targetVolumePath: '/github/workflow',
      readOnly: false
    },
    {
      userProvidedValue: null,
      sourceVolumePath: '/home/nikola/Projects/runner-hooks/_layout/_work/_temp/_runner_file_commands',
      targetVolumePath: '/github/file_commands',
      readOnly: false
    },
    {
      userProvidedValue: null,
      sourceVolumePath: '/home/nikola/Projects/runner-hooks/_layout/_work/my-hook-test/my-hook-test',
      targetVolumePath: '/github/workspace',
      readOnly: false
    }
  ],
  userMountVolumes: []
}
```
Now, since this is a Dockerfile action, we should have a field `args.dockerfile`. Also, the content of the `args.dockerfile` should be an absolute path to the Dockerfile in question. In other words: `$PATH_TO_THE_RUNNER/_layout/_work/_actions/nikola-jokic/composite/main/cont/Dockerfile`

Also, should I have a NULL for the `registry` if the registry is not specified? If this is what is decided, then we should update the hook reflecting this change. Previously, if registry was not provided, we have been checking if it is falsy (`null` or `undefined`). I can submit this as another issue.
